#!/bin/bash

dataDir="/mnt/usbdrive/ghost-1.0/content"
blogDir="/var/lib/ghost/content"
GHOST_VERSION="1.17.3"

docker pull kennethlimcp/armhf-ghost:$GHOST_VERSION

if [ $? -ne 0 ]
then
  echo "unable to download image"
  exit
fi

docker rm -f ghostblog

docker run --rm \
--name ghostmigrate \
-v  $dataDir:$blogDir \
-e "NODE_ENV=production" \
kennethlimcp/armhf-ghost:$GHOST_VERSION \
ghost setup migrate

docker run -d \
-p 8080:2368 \
--restart=always \
--name ghostblog \
-v  $dataDir:$blogDir \
kennethlimcp/armhf-ghost:$GHOST_VERSION

docker logs -f ghostblog
